matrix:
  include:
  - services:
    - docker
    name: Docker Version
    script:
      - docker --version
  - services:
    - docker
    name: Amazon Linux 1
    script:
      - ./Dockerfiles/amazonlinux/1/manage.sh build clean
  - services:
    - docker
    name: Amazon Linux 2
    script:
      - ./Dockerfiles/amazonlinux/2/manage.sh build clean
  - services:
    - docker
    name: Centos 7
    script:
      - ./Dockerfiles/centos/7/manage.sh build clean
  - services:
    - docker
    name: Centos 8
    script:
      - ./Dockerfiles/centos/8/manage.sh build clean
  - services:
    - docker
    name: Debian 9 (Stretch)
    script:
      - ./Dockerfiles/debian/9/manage.sh build clean
  - services:
    - docker
    name: Debian 9 (Stretch Slim)
    script:
      - ./Dockerfiles/debian/9-slim/manage.sh build clean
  - services:
    - docker
    name: Debian 10 (Buster)
    script:
      - ./Dockerfiles/debian/10/manage.sh build clean
  - services:
    - docker
    name: Debian 10 (Buster Slim)
    script:
      - ./Dockerfiles/debian/10-slim/manage.sh build clean
  - services:
    - docker
    name: Debian 11 (Bullseye)
    script:
      - ./Dockerfiles/debian/11/manage.sh build clean
  - services:
    - docker
    name: Debian 11 (Bullseye Slim)
    script:
      - ./Dockerfiles/debian/11-slim/manage.sh build clean
  - services:
    - docker
    name: Ubuntu 16.04 (Xenial Xerus / Xenial)
    script:
      - ./Dockerfiles/ubuntu/16.04/manage.sh build clean
  - services:
    - docker
    name: Ubuntu 18.04 (Bionic Beaver / Bionic)
    script:
      - ./Dockerfiles/ubuntu/18.04/manage.sh build clean
  - services:
    - docker
    name: Ubuntu 20.04 (Focal Fossa / Focal)
    script:
      - ./Dockerfiles/ubuntu/20.04/manage.sh build clean
  - services:
    - docker
    name: Dockerfile Linting (Hadolint)
    before_install:
    - git clone https://github.com/TravisToolbox/hadolint
    install:
    - "./hadolint/install.sh"
    script:
    - "./hadolint/scan.sh"
  - language: ruby
    name: Github Linguist (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/github-linguist
    install:
    - "./github-linguist/install.sh"
    script:
    - "./github-linguist/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 2.7)
    rvm: 2.7
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: Gqm31pXA8L9oqmTddneCEx/HFsZJkNxJd0cujsTbSoyODYtFwGOz8+JtpAtc36vYyJi7XFhECKZSVLRcQXrD5/c53w86zxUHYI16kVYb2zHCm3+jl4Cak5+X8btzVUrC902Op0bH6tCIf1SWBuSsYgaH2Ot2ksUTt9Frx83ozQnBM/Jt21Kv5zMmMx2dFuki4vX+8fHlyPS11pcntCVpJFlcxXZEMl4K3jDg5dAeKi+EOiNcT3bgunzP89c5DUGrgi3+MkwAc5EREeJ09AwOAWcQmtUkzg29gFQuM6kZ4e84Fkxh+P09SXa+9TaInqMea4f59LHJ4UDgfNkbHufe9GUXEDwvvdB6wZ895n8wpi2RzT+nODolzSMSULqDXT7IH2iBpuuiFQxMTOPEDzsCIeiQCVjZdnKKr/y7Mnka4fZY1aE8VbskNaJf327CbKKVArEKQ3pc4eliU8xrsKp56zGoWE4lQqUeCkZvpER6Y7wENlsjEqNvkqw6ZzBtCYBqsR2mOAjo+xYy+j3eYxaPzvExRDLRlseF5MaQo6/bU5bHa4Om36lSq0bPREtQQ6jraKoP6FWUSUV3Bgu+TvpHAj+lhf0i2l7p6PyjnR52X04vcKcbBmVnK2codLzJwhexuwQyoZRlTvLpVRAvp/aE/JEYwLwbU4CIt6hL5Dwwi4o=
